URL_SERVICE = "https://cnt-ac2011df-feec-4ec4-98f1-b9c30ed1422b.containerhub.tripleten-services.com/docs"
DOC_PATH = "/docs"
LOG_MAIN_PATH = "/logs"
USERS_TABLE_PATH = "/users/table"
CREATE_USER_PATH = "/users/create"
PRODUCTS_KITS_PATH = "/products/kits"
