URL_SERVICE = "https://cnt-b2fa7df5-6ddf-4a2d-9db2-f00056725414.containerhub.tripleten-services.com/"
DOC_PATH = "/docs"
LOG_MAIN_PATH = "/logs"
USERS_TABLE_PATH = "/users/table"
CREATE_USER_PATH = "/users/create"
PRODUCTS_KITS_PATH = "/products/kits"
